# Generated by Django 4.0.3 on 2022-04-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('salary_type', models.CharField(blank=True, choices=[('lei', 'Lei'), ('euro', 'Euro'), ('dolar', 'Dolari')], max_length=10, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('project', 'Temporar'), ('others', 'Altele')], default='full_time', max_length=10, null=True)),
                ('contract_type', models.CharField(blank=True, choices=[('determined', 'Determinat'), ('undetermined', 'Nedeterminat'), ('internship', 'Internship'), ('collaboration', 'Colaborare')], default='undetermined', max_length=15, null=True)),
                ('education', models.CharField(blank=True, choices=[('unqualified', 'Necalificat'), ('qualified', 'Calificat'), ('student', 'Student')], default='unqualified', max_length=15, null=True)),
                ('local_or_distance', models.CharField(blank=True, choices=[('local', 'La fața locului'), ('distance', 'De la distanță'), ('hibrid', 'Regim hibrid')], default='local', max_length=10, null=True)),
                ('experience', models.CharField(blank=True, choices=[('trainee', 'Stagiar'), ('beginner', 'Începător (< 2ani)'), ('mediu', 'Nivel mediu de experienta (2-5 ani)'), ('senior', 'Senior-level (> 5ani)'), ('manager', 'Manager / Executiv')], default='beginner', max_length=10, null=True)),
                ('release', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/ad')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
