# Generated by Django 4.0.3 on 2022-04-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='telefon:'),
        ),
    ]
