# Generated by Django 4.0.3 on 2022-04-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_ad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='contract_type',
            field=models.CharField(choices=[('determined', 'Determinat'), ('undetermined', 'Nedeterminat'), ('internship', 'Internship'), ('collaboration', 'Colaborare')], default=2021, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='education',
            field=models.CharField(choices=[('unqualified', 'Necalificat'), ('qualified', 'Calificat'), ('student', 'Student')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='experience',
            field=models.CharField(choices=[('trainee', 'Stagiar'), ('beginner', 'Începător (< 2ani)'), ('mediu', 'Nivel mediu de experienta (2-5 ani)'), ('senior', 'Senior-level (> 5ani)'), ('manager', 'Manager / Executiv')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default=1, upload_to='static/ad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('project', 'Temporar'), ('others', 'Altele')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='local_or_distance',
            field=models.CharField(choices=[('local', 'La fața locului'), ('distance', 'De la distanță'), ('hibrid', 'Regim hibrid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='telefon:'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='salary_type',
            field=models.CharField(choices=[('lei', 'Lei'), ('euro', 'Euro'), ('dolar', 'Dolari')], max_length=10),
        ),
    ]
